### ISSUE TITLE
MKS Smini PINs

### ISSUE THREAD

**Issue by DaGov** [makerbase-mks/MKS-SBASE#12]
Need MKS Smini PIN diagram for connection. Or create new branch for this board with info.

**Comment by brunnels** [comment]
The best I found was this https://img.alicdn.com/imgextra/i3/12778391/TB2S7lguXXXXXXEXpXXXXXXXXXX_!!12778391.png

The problem is I'm assuming the 16/128 jumper headers is for switching between 16/128 microstepping but is there any option in between?  Also there is the 4 position switch that is labeled as "SDCard Switch" but no documentation on that.

**Comment by makerbase-mks** [comment]
mks smini only have 16 and 128, can't use  other microstep.
SDCard Switch is used to set if use sdcard on board and sdcard on 12864lcd at the same time or only use sdcard on board . On normal time, it is not useful
