### ISSUE TITLE
What is DRV8825 decay mode used by board?

### ISSUE THREAD

**Issue by egorse** [makerbase-mks/MKS-SBASE#14]

**Comment by pixel3design-hub** [comment]
If you mean Fast Decay Mode, it's an internal function of the DRV8825. It's a good function badly implemented, even in the original Smoothieware Hardware. It needs diodes in reverse parallel on two channels of the output to stop motor making terrible noise in 1/32 step mode, just because current phase control is generating harmonics and sub harmonics from the 30KHz pulse signal that chip is working on.

Kinda of...

**Comment by egorse** [comment]
I am on pin 19 - is that low, open or high?

But thanks for prompt reply!

**Comment by pixel3design-hub** [comment]
Low = slow decay, open = mixed decay,
high = fast decay.
Internal pulldown and pullup.

**Comment by egorse** [comment]
I can see that from datasheet - but whats on the PCB/assembly?

**Comment by tiaanv** [comment]
I second the request.  Is the PCB wired to put the DRV8825 in fast decay mode or is is mixed mode?  Would not be able to see unless I remove the heatsink which I would not like to do.  Listening to it in operation, I think it might be in Mixed mode.  Please confirm.

**Comment by Steamerzone** [comment]
As far as I can measure it, it's running in mixed decay mode. (decay pin is open)

**Comment by makerbase-mks** [comment]
MKS Sbase's drv8825 all use mixed decay mode.

**Comment by feket663** [comment]
Can I use this board with 24 power supply and relativly high inductance stepper motors with low current? Need enable fast decay mode?
