### ISSUE TITLE
What does the row of LEDs indicate

### ISSUE THREAD

**Issue by Hoverhead** [makerbase-mks/MKS-SBASE#31]
What to the various LEDs in the row of 5 indicate?
What does the two flashing ones indicate?
What is happening when these LEDs are all steady light?
What is happening after the first, second and third press of the reset button?
Sometimes the board stops after using Chrome to log on to it.  Often takes 3 or 4 resets before the row of LEDs  go 2 flashing and 3 steady.  What is happening here?

**Comment by pixel3design-hub** [comment]
Hi.
As I can traceback from the board, the MKS-SBASE is a mere knock-off of the SmoothieBoard.
Refer to [SmoothieBoard Schematics](http://forum.smoothieware.org/printer--friendly//smoothieboard-schematic) at link provided.
As far as I know, one is for USB ACTIVE (if you disable USB HOST it should be darkened),one for USB POWER, two for PWM 0 and 1 and last one... I don't know.

Steady light means board STUCK.

If your board hangs, it's because of a known HARDWARE bug. In early versions they put a resonator instead of a crystal, to take down costs. But USB and Ethernet requires a really steady OSC/CRYSTAL signal to work correctly, 5ppm to be exact. Resonator has a way loose frequency sweeping, around 50ppm, unacceptable for strong USB or Ethernet connections. They updated the board an year ago, turning to a Crystal with 10ppm. I personally use the TFT32 module, so I don't need the USB or the ethernet.

Reset is a little erratic. I don't know any solutions.

In hope to be helpful, Cheers dude.

**Comment by Hoverhead** [comment]
Thanks for that. I looked at the schematic, don't really understand it though.  The hint to the key was helpful.  I have also recently installed a TFT32 but have found it too useful yet as it doesn't have wifi and it doesn't seem to want to read my usb drives.  I think I might have to resort back to pronterface as the web GUIs are pretty ordinary to say the least.
