### ISSUE TITLE
SDcard speed

### ISSUE THREAD

**Issue by whoopi4** [makerbase-mks/MKS-SBASE#63]
Hello !

I bought a MKS sBase Controller and i want to test it last weekend.
I installed the USB Driver on Windows 7. It works an a see the Sbase on my workbench.
It works but extremly slow.
When i put the webos folder on the sdcard it works only with 18KB/s !
And the same speed when i connect over Network and upload a gcode files ....

Where ist the problem ? On the firmware or on the config file ? ( I use the std-config )

greatings Rainer !

**Comment by pixel3design-hub** [comment]
The USB connection is a serial connection in reality. @18K/s my assumption
is you set the connection to 250000 baud.
Taking out the parity bit and you almost got it... If you want speed, use
the ethernet instead of USB.
Cheers



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

2018-01-22 16:17 GMT+01:00 whoopi4 <notifications@github.com>:
