### ISSUE TITLE
Printer stops constantly during print

### ISSUE THREAD

**Issue by KuroiSabato** [makerbase-mks/MKS-SBASE#79]
Have a sbase v1.3, tft 32 connected to a mks Power Outage detector and a mks  PWC.

the print starts normally, but  randomly stops completely for some seconds and than continues the print. It does that multiple times during the print. No need to say, the print comes out useless.
Need also to say, that it has burned 3 24v fans in the last 2 weeks, so the board is clearly over powering the components... 
what could the problem be, and how can it be fixed?

**Comment by KuroiSabato** [comment]
??? Any support?

**Comment by pixel3design-hub** [comment]
Not from makerbase...
Board just stop the flow of the current for heaters and fans via mosfets creating pwm signals that can only lower the the current, never raise it. Are you sure that fans are 24v tolerants? If yes, than put a voltmeter in the 24v power rail and be sure that is stable with no peaks. Power supplies from China are not well regulated and you should have calibrate it BEFORE connecting it to the board.
Which board you got? A v3 or a v2? Last option have a bug in the USB and Ethernet. MKS puts a resonator instead of a crystal in those boards, which is drifting too much in frequency. A crystal is needed with a tolerance of 5ppm.
My suggestion is to use an 12864 display with SD card to print.
This involves some pin swapping in cables, but it worth the time.
Ask me if need more support. I'm not involved with MKS in any way, but I got many boards and learned a lot from them...
Cheers dude
