### ISSUE TITLE
MKS-SBASE v1.3 not woking

### ISSUE THREAD

**Issue by MeikVr6** [makerbase-mks/MKS-SBASE#96]
Dear guys,
I have a following problem
My new board don't work. I have download and configuration the firmeware and config.txt from this site.
I have update the Firmeware over the a 2GB Micro SD-Card. In the SD-Card stand after the Update firmeware.CUR Data file.
What is my mistake?
[config.txt](https://github.com/makerbase-mks/MKS-SBASE/files/2835336/config.txt)
[firmware.zip](https://github.com/makerbase-mks/MKS-SBASE/files/2835342/firmware.zip)

Thanks for the Help

**Comment by BorgMaster** [comment]
Same problem, nothing seems to move. Any ideas ?

**Comment by MeikVr6** [comment]
Hello
I would like testing the MKS sbase with Marlin.

BR
Meik

**Comment by makerbase-mks** [comment]
After updating the configuration file through the sd card, whether to ensure that the sd card is inserted on the motherboard every time the power is turned on. Because every time you boot the motherboard, you need to read the parameters in the configuration file from the sd card. When the motherboard is powered on, there is no SD card inserted or there is no configuration file in the card. The motherboard can't read the data, it can't be used.
